### ISSUE TITLE
Install to Symfony 2.1.9 faild

### ISSUE THREAD

**Issue by Evgenas** [artberri/BerriartSitemapBundle#15]
tried to install it to Symfony 2.1.9 and got follow error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/symfony v2.1.9
    - Conclusion: don't install symfony/symfony v2.1.9
    - Conclusion: don't install symfony/symfony v2.1.8
    - Conclusion: don't install symfony/symfony v2.1.7
    - Conclusion: don't install symfony/symfony v2.1.6
    - Conclusion: don't install symfony/symfony v2.1.5
    - Conclusion: don't install symfony/symfony v2.1.4
    - Conclusion: don't install symfony/symfony v2.1.3
    - Installation request for berriart/sitemap-bundle dev-master -> satisfiable by berriart/sitemap-bundle dev-master.
    - Conclusion: don't install symfony/symfony v2.1.2
    - Conclusion: don't install symfony/symfony v2.1.1
    - berriart/sitemap-bundle dev-master requires symfony/doctrine-bundle * -> satisfiable by symfony/symfony 2.0.7, symfony/symfony v2.0.10, symfony/symfony v2.0.11, symfony/symfony v2.0.12, symfony/symfony v2.0.13, symfony/symfony v2.0.14, symfony/symfony v2.0.15, symfony/symfony v2.0.16, symfony/symfony v2.0.17, symfony/symfony v2.0.18, symfony/symfony v2.0.19, symfony/symfony v2.0.20, symfony/symfony v2.0.21, symfony/symfony v2.0.22, symfony/symfony v2.0.23, symfony/symfony v2.0.9.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony 2.0.7.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.10.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.11.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.12.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.13.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.14.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.15.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.16.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.17.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.18.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.19.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.20.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.21.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.22.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.23.
    - Can only install one of: symfony/symfony v2.1.0, symfony/symfony v2.0.9.
    - Installation request for symfony/symfony 2.1.* -> satisfiable by symfony/symfony v2.1.0, symfony/symfony v2.1.1, symfony/symfony v2.1.2, symfony/symfony v2.1.3, symfony/symfony v2.1.4, symfony/symfony v2.1.5, symfony/symfony v2.1.6, symfony/symfony v2.1.7, symfony/symfony v2.1.8, symfony/symfony v2.1.9.

**Comment by artberri** [comment]
That was a conflict between the symfony version that different plugin required, sorry for being late on answering. That version is not supported anymore but I suppose that you have upgraded already :S
